name: tfsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
  schedule:
    - cron: '33 15 * * 4'

jobs:
  tfsec:
    name: tfsec report
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    defaults:
      run:
        working-directory: ./Cloud

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-sarif-action@9a83b5c3524f825c020e356335855741fd02745f
        with:
          sarif_file: tfsec.sarif         

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif  
